# Generated by Django 5.2.4 on 2025-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_titular', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('ci_beneficiario', models.CharField(max_length=20)),
                ('parentesco', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('discapacidad', models.CharField(blank=True, max_length=100)),
                ('custodia_legal', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
